<template><div class="page"><p class="intro">同期对照、月度趋势与商品金额贡献。州筛选作用于全页；月份筛选作用于趋势和排名。</p><Filters/><div class="filters comparison-filter"><label>同期年份<input type="number" aria-label="对照年份" v-model.number="window.year_a" min="1900" max="9997"></label><span>与</span><input type="number" aria-label="比较年份" v-model.number="window.year_b" min="1901" max="9998"><label>共同月份<input type="number" aria-label="同期开始月" v-model.number="window.month_from" min="1" max="12"></label><span>至</span><input type="number" aria-label="同期结束月" v-model.number="window.month_to" min="1" max="12"><button @click="load">应用同期窗口</button></div><div v-if="error" class="error">{{error}}</div><div v-if="!state.meta?.ready" class="empty">请先构建数据层。</div><template v-else-if="data"><section class="panel"><div class="panel-title"><h2>同期指标与增幅</h2><small>{{data.window.month_from}}—{{data.window.month_to}} 月，两个年份使用同一窗口</small></div><table><thead><tr><th>指标</th><th>{{data.window.year_a}}</th><th>{{data.window.year_b}}</th><th>同比变化</th></tr></thead><tbody><tr v-for="(label,key) in metricLabels" :key="key"><td>{{label}}{{['product_value','aov','price_per_item'].includes(String(key))?'（R$）':''}}</td><td>{{number(data.comparison[0][key],['aov','orders_per_customer','items_per_order','price_per_item'].includes(String(key))?2:0)}}</td><td>{{number(data.comparison[1][key],['aov','orders_per_customer','items_per_order','price_per_item'].includes(String(key))?2:0)}}</td><td :class="data.change[key]>0?'positive':''">{{data.change[key]>0?'+':''}}{{pct(data.change[key],2)}}</td></tr></tbody></table><p class="footnote">商品金额 = 订单数 × 商品客单价；商品客单价 = 单均件数 × 件均价格。人均订单数为当前窗口的订单数／客户数。</p></section><div class="two-col"><section class="panel"><h2>商品客单价 · 月度趋势</h2><Chart :option="line(data.monthly,['aov'],['商品客单价（R$）'])"/></section><section class="panel"><h2>人均已送达订单 · 月度趋势</h2><Chart :option="line(data.monthly,['orders_per_customer'],['人均订单数'],false,2,false)"/><p class="footnote">人均订单数不等于复购率；纵轴随数据范围变化。</p></section></div><div class="three-col"><section class="panel" v-for="(title,key) in dimensions" :key="key"><h2>{{title}} · 商品金额 Top 10</h2><Chart :option="bars(data.ranking[key])" height="400px"/><div class="concentration"><span>Top 1 <b>{{pct(data.concentrations[key].top1_share)}}</b></span><span>Top 10 <b>{{pct(data.concentrations[key].top10_share)}}</b></span><span>HHI <b>{{number(data.concentrations[key].hhi)}}</b></span></div><details><summary>查看金额贡献与订单数</summary><table class="compact"><thead><tr><th>对象</th><th>金额贡献</th><th>订单数</th></tr></thead><tbody><tr v-for="r in data.ranking[key]" :key="r.name"><td :title="r.name">{{r.name}}</td><td>{{pct(r.amount_share)}}</td><td>{{number(r.orders)}}</td></tr></tbody></table></details></section></div><p class="footnote">品类与卖家金额取商品项 Mart，州金额取订单 Mart。品类／卖家订单数可能交叉，不能直接相加。HHI = 全部对象金额份额平方和 × 10,000；Top 10 在当前月份和州范围内重新计算。</p></template></div></template>
<script setup lang="ts">
import {ref,reactive,watch,onMounted,onBeforeUnmount} from 'vue'
import {state,api,query,number,pct,metricLabels} from '../state';import Filters from '../components/Filters.vue';import Chart from '../components/Chart.vue';import {line,bars} from '../charts'
const data=ref<any>(null),error=ref(''),window=reactive({year_a:2017,year_b:2018,month_from:1,month_to:8});const dimensions={state:'客户州',category:'品类',seller:'卖家'};let request=0,initialized=false
async function load(){if(!state.meta?.ready)return;if(!initialized){Object.assign(window,{year_a:state.meta.defaults.year_a,year_b:state.meta.defaults.year_b,month_from:1,month_to:state.meta.defaults.month_to});initialized=true} const current=++request;try{const result=await api('/api/reports/growth?'+query(window));if(current===request){data.value=result;error.value=''}}catch(e:any){if(current===request)error.value=e.message}}
watch(()=>[state.meta?.ready,...Object.values(state.filter)],load,{immediate:true})
onMounted(()=>globalThis.window.addEventListener('olist-refresh',load));onBeforeUnmount(()=>globalThis.window.removeEventListener('olist-refresh',load))
</script>
