<template><div class="page"><p class="intro">按购买月份查看最终订单结果；已送达商品金额不含运费。</p><Filters/><div v-if="error" class="error">{{error}}</div><div v-if="!state.meta?.ready" class="empty">完成三层数据构建后，经营报表将在这里更新。</div><template v-else-if="data"><div class="kpi-grid"><article class="kpi" v-for="key in ['product_value','delivered_orders','customers','aov']" :key="key"><span>{{metricLabels[key]}}</span><strong>{{key==='product_value'||key==='aov'?'R$ ':''}}{{number(data.summary[key],key==='aov'?2:0)}}</strong><small>{{key==='aov'?'商品金额 ÷ 已送达订单数':key==='customers'?'customer_unique_id 去重':key==='product_value'?'已送达订单商品金额':'按 order_id 去重'}}</small></article></div><section class="panel"><div class="panel-title"><h2>商品金额 · 月度趋势</h2><small>单位：R$</small></div><Chart :option="line(data.monthly,['product_value'],['商品金额'])"/></section><div class="two-col"><section class="panel"><h2>订单数与客户数 · 月度趋势</h2><Chart :option="line(data.monthly,['delivered_orders','customers'],['已送达订单','已送达客户'])"/></section><section class="panel"><h2>延迟率与低评分率 · 月度趋势</h2><Chart :option="line(data.monthly,['late_rate','low_score_rate'],['延迟率','低评分率'],true)"/><p class="footnote">延迟率分母：可判断准时性的已送达订单；低评分率分母：有 1–5 分有效评价的已送达订单。低评分为 ≤3 分。</p></section></div><section class="panel"><h2>指标与样本数</h2><div class="table-wrap"><table><thead><tr><th>月份</th><th>商品金额（R$）</th><th>已送达订单</th><th>客户数</th><th>客单价（R$）</th><th>延迟率</th><th>准时性样本</th><th>低评分率</th><th>评价样本</th></tr></thead><tbody><tr v-for="r in data.monthly" :key="r.month"><td>{{r.month}}</td><td>{{number(r.product_value,2)}}</td><td>{{number(r.delivered_orders)}}</td><td>{{number(r.customers)}}</td><td>{{number(r.aov,2)}}</td><td>{{pct(r.late_rate)}}</td><td>{{number(r.delivery_sample)}}</td><td>{{pct(r.low_score_rate)}}</td><td>{{number(r.review_sample)}}</td></tr></tbody></table></div></section><p class="footnote">客户数在当前筛选范围内去重，月度客户数之和不一定等于总客户数。无有效样本的比例留空；历史首末月份可能不完整。</p></template><div v-else class="empty">正在加载报表…</div></div></template>
<script setup lang="ts">
import {ref,watch,onMounted,onBeforeUnmount} from 'vue'
import {state,api,query,number,pct,metricLabels} from '../state'
import Filters from '../components/Filters.vue';import Chart from '../components/Chart.vue';import {line} from '../charts'
const data=ref<any>(null),error=ref('');let request=0
async function load(){if(!state.meta?.ready)return;const current=++request;try{const result=await api('/api/reports/overview?'+query());if(current===request){data.value=result;error.value=''}}catch(e:any){if(current===request)error.value=e.message}}
watch(()=>[state.meta?.ready,...Object.values(state.filter)],load,{immediate:true})
onMounted(()=>window.addEventListener('olist-refresh',load));onBeforeUnmount(()=>window.removeEventListener('olist-refresh',load))
</script>
